### ISSUE TITLE
How can i pass/connect variables between the Capture project and the TestScreenshot project ?

### ISSUE THREAD

**Issue by Csharper1972** [spazzarama/Direct3DHook#23]
For example i create a public variable type bool in the TestScreenshot project and now i want to use this variable in the Capture project so when i set for example in the TestScreenshot if i click on a button and change the bool variable to false when i use it in the Capture project it will be false and if i click on another button then it will be true also in the Capture project.

**Comment by spazzarama** [comment]
You could setup a MarshalByRef class (kind of like the Screenshot class), or you could use an event handler (see the Capture interface and how it handles events).

**Comment by Csharper1972** [comment]
Thank you i will look into it.
