### ISSUE TITLE
Cannot move files, C++ error

### ISSUE THREAD

**Issue by HACKHERS** [spazzarama/Direct3DHook#37]
All the files are in the /bin/ folder it works fine for example i move /bin/ folder to c:\ it doesnt working giving Capture.InjectionFailedException: Injection to the target process failed. See InnerException for more detail. ---> System.ApplicationException: STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)

**Comment by spazzarama** [comment]
What do you mean by "i move /bin/ folder to c:\"? Do you mean you are moving the files from bin into C:\ or you are moving the files into C:\bin?

If moving into C:\ root then you will have issues with needing to run as administrator etc...

**Comment by HACKHERS** [comment]
It doesn't matter where I move the files, I tried everything like moving files from /bin/ folder to /bin/test/ folder still giving error.

**Comment by spazzarama** [comment]
What was the problem in the end?

**Comment by HACKHERS** [comment]
I have no idea, after upgrading windows 10 problem is solved :)
