### ISSUE TITLE
Screenshot background window

### ISSUE THREAD

**Issue by Kuhicop** [spazzarama/Direct3DHook#74]
Hello, this is more a question than an issue but I hope someone can help

It's possible to take screenshots from a background window without setting it as foreground?

If it's possible, how can I do it?

Thank you

**Comment by spazzarama** [comment]
This already does it, but not if minimised (if Direct3D). Otherwise GDI BitBlt might work.

**Comment by Kuhicop** [comment]
Please could you tell me how to do it without setting the window at front (foreground)?

When I run the TestScreenshot form it's taking the window to front and taking the screenshot but what I need is taking a screenshot from a window without bringing to front

Thank you very much and sorry for reopen

**Comment by spazzarama** [comment]
Exactly what I was going to suggest, enjoy.
